
import os
import glob
import time
import asyncio
import logging
import math
from yahub import Msg, Yahub, TerminateTaskGroup

class Yonewire:

  queue = asyncio.Queue(maxsize=100)

  def __init__(self, yahub, config, root):
    self.config = config
    self.root = root
    self.yahub = yahub
    self.logger = logging.getLogger()

    # Base directory for 1-Wire devices
    self.base_dir = '/sys/bus/w1/devices/'


  async def run(self):
    try :
      self.logger.debug('coroutine started')
      """
      Scans for all sensors and reads their temperatures.
      """
      self.logger.info(f"one time scan for DS18B20 sensors")
      # Pattern to find all DS18B20 sensor directories
      self.sensor_folders = glob.glob(self.base_dir + '28-*')
      self.logger.info(f"found {len(self.sensor_folders)} DS18B20 sensors.")
      while True:
        await self.read_all_sensors()
        await asyncio.sleep(self.config.get(self.root, 'poll_interval', 20))
    except Exception as ex:
      self.logger.exception(f'coroutine stopping {ex}')
      raise TerminateTaskGroup();
    finally:
      pass


  async def read_temp_raw(self, device_folder):
    """
    Reads the raw data lines from the sensor's w1_slave file.
    """
    try:
      device_file = device_folder + '/w1_slave'
      with open(device_file, 'r') as f:
        lines = f.readlines()
      return lines
    except FileNotFoundError:
      raise FileNotFoundError(f"Could not find w1_slave file for {device_folder}. Check wiring/setup.")

  """
  methods below generated by google Gemini
  """
  async def read_temp_celsius(self, device_folder):
    """
    Parses the raw data to extract the temperature in Celsius.
    Returns None on a failed CRC check.
    """
    lines = await self.read_temp_raw(device_folder)
    if not lines:
      return None

    # Check for successful data read (CRC check)
    while lines[0].strip()[-3:] != 'YES':
      await asyncio.sleep(0.2)
      lines = await read_temp_raw(device_folder)
      if not lines:
        return None # Exit if file disappears

    # Find the temperature data (t=)
    equals_pos = lines[1].find('t=')
    if equals_pos != -1:
      temp_string = lines[1][equals_pos+2:]
      # Temperature is in millidegrees Celsius
      temp_c = float(temp_string) / 1000.0
      return temp_c
    return None



  async def read_all_sensors(self):
    """
    reads temperatures.
    """
    self.logger.debug(f"reading temperatures")
    timestamp = math.floor(time.time())   # no rounding
    msgs = []
    for folder in self.sensor_folders:
      # Extract the sensor ID from the folder path
      sensor_id = folder.split('/')[-1]
      temp_c = await self.read_temp_celsius(folder)
      if temp_c is not None:
#       self.logger.debug(f"Sensor ID: {sensor_id} | Temperature: {temp_c:.3f}°C")

        sensorMap      = self.config.get(self.root, 'sensor-map', {})
        sensorLocation = self.config.get(self.root, 'sensor-location', {})
        sensorName = None ;
        sensorOffset = 0 ;
        # first lookup
        device = sensorMap[sensor_id] if sensor_id in sensorMap else sensor_id

        if type(device) is list:
          sensorName = device[0]
          sensorOffset = device[1]
          temp_c += device[1]
        else:
          sensorName = device

        self.logger.debug(f"Sensor ID: {sensor_id}, name: {sensorName}, offset: {sensorOffset}")

        msg = Msg(f"onewire/{sensorName}", round(temp_c, 2))
        msg.timestamp = timestamp
        msg.measurement = self.config.get(self.root,'measurement','temperature') ;

        if sensorName in sensorLocation :
          msg.source = sensorName ;
          msg.location = sensorLocation[sensorName]
          #
          # set up the influx fields
          #
          self.logger.debug(f'location w optional tag is {msg.location}')
          if type(msg.location) is list:

            msg.fields = { msg.location[0] : temp_c }
            msg.tags   = { 'source' : msg.location[1] }

          else:
            msg.fields = { msg.location : temp_c }
            msg.tags   = { 'source' : msg.source }

        else :
          msg.source = sensorName ;
          #
          # set up the influx fields
          #
          msg.fields = { msg.source : temp_c }
          msg.tags   = { }

        self.logger.debug(f'queued: {msg}')
        msgs.append(msg)

      else:
        self.logger.warning(f"Sensor ID: {sensor_id} | Error reading temperature.")

    self.yahub.route(msgs);

