
import os
import glob
import time
import asyncio
import logging
import math
from yahub import Msg, Yahub, TerminateTaskGroup

class Yonewire:

  queue = asyncio.Queue(maxsize=100)

  def __init__(self, yahub, config, root):
    self.config = config
    self.root = root
    self.yahub = yahub
    self.logger = logging.getLogger()

    # Base directory for 1-Wire devices
    self.base_dir = '/sys/bus/w1/devices/'
    # Pattern to find all DS18B20 sensor directories
    self.sensor_folders = glob.glob(self.base_dir + '28-*')
    self.source = 'onewire' ;


  async def run(self):

    self.logger.debug('coroutine started')

    while True:
      val = await self.scan_and_read_all()
      await asyncio.sleep(self.config.get(self.root, 'poll_interval', 20))
    self.logger.exception(f'coroutine stopping {ex}')
    raise TerminateTaskGroup();



  async def read_temp_raw(self, device_folder):
    """
    Reads the raw data lines from the sensor's w1_slave file.
    """
    try:
        device_file = device_folder + '/w1_slave'
        with open(device_file, 'r') as f:
            lines = f.readlines()
        return lines
    except FileNotFoundError:
        raise FileNotFoundError(f"Error: Could not find w1_slave file for {device_folder}. Check wiring/setup.")

  """
  methods below generated by google Gemini
  """

  async def read_temp_celsius(self, device_folder):
    """
    Parses the raw data to extract the temperature in Celsius.
    Returns None on a failed CRC check.
    """
    lines = await self.read_temp_raw(device_folder)
    if not lines:
        return None

    # Check for successful data read (CRC check)
    while lines[0].strip()[-3:] != 'YES':
        await asyncio.sleep(0.2)
        lines = await read_temp_raw(device_folder)
        if not lines:
            return None # Exit if file disappears

    # Find the temperature data (t=)
    equals_pos = lines[1].find('t=')
    if equals_pos != -1:
        temp_string = lines[1][equals_pos+2:]
        # Temperature is in millidegrees Celsius
        temp_c = float(temp_string) / 1000.0
        return temp_c
    return None



  async def scan_and_read_all(self):
    """
    Scans for all sensors and reads their temperatures.
    """
    if not self.sensor_folders:
      raise Exception("No DS18B20 sensors found. Check wiring/1-Wire enablement.")

    self.logger.debug(f"Reading Temperatures")
    timestamp = (math.floor(time.time()))   # no rounding
    msgs = []
    for folder in self.sensor_folders:
      # Extract the sensor ID from the folder path
      sensor_id = folder.split('/')[-1]
      temp_c = await self.read_temp_celsius(folder)
      if temp_c is not None:
#       self.logger.debug(f"Sensor ID: {sensor_id} | Temperature: {temp_c:.3f}°C")

        sensorMap = self.config.get(self.root, 'sensor-map', {})
        # first lookup
        sensorName = sensorMap[sensor_id] if sensor_id in sensorMap else sensor_id[-4:]
        # try to get sensor location from same table e.g. 'flowOut'
        location = sensorMap[sensorName] if sensorName in sensorMap else sensorName
        msg = Msg(f"{self.source}/{sensorName}", round(temp_c, 2))
        msg.timestamp = timestamp
        msg.source = self.source
        #
        # set up the influx fields
        #
        msg.measurement = 'temperature' ;
        msg.fields = { location : temp_c }
        msg.tags   = { source   : self.source }
        self.logger.debug(f'queued: {msg}')
        msgs.append(msg)

      else:
          self.logger.warning(f"Sensor ID: {sensor_id} | Error reading temperature.")

    self.yahub.route(msgs);

